/* Enhancements for the portable, dependency-free attribution game. */
(() => {
  'use strict';
  const $ = (id) => document.getElementById(id);
  const today = new Date().toISOString().slice(0, 10);
  const storageKey = 'who-said-it:best-points:v2';
  const session = { mode: 'quick', points: 0, streak: 0, bestStreak: 0, confidence: null, timelineReady: true, timelineCorrect: null, rounds: [] };
  const store = { get: () => { try { return Number(localStorage.getItem(storageKey)) || 0; } catch { return 0; } }, set: (value) => { try { localStorage.setItem(storageKey, value); } catch {} } };

  function auditBank() { const ids = new Set(); const errors = []; BANK.forEach((d, i) => { if (!d?.id || ids.has(d.id)) errors.push(`Duplicate or missing id at ${i + 1}`); ids.add(d?.id); if (!['nazi', 'israel'].includes(d?.group) || !d?.speaker || !d?.quote || !d?.masked || !d?.source || !d?.context) errors.push(`Incomplete record ${d?.id || i + 1}`); try { if (!/^https?:$/.test(new URL(d.url).protocol)) errors.push(`Unsafe URL for ${d.id}`); } catch { errors.push(`Invalid URL for ${d?.id || i + 1}`); } }); return { valid: !errors.length, records: BANK.length, errors }; }
  const audit = auditBank(); document.documentElement.dataset.bank = audit.valid ? 'checked' : 'needs-review';
  function seeded(seed) { let x = [...seed].reduce((n, char) => ((n << 5) - n + char.charCodeAt(0)) | 0, 0) || 1; return () => ((x = (x * 1664525 + 1013904223) >>> 0) / 4294967296); }
  function shuffleWith(items, random = Math.random) { const next = [...items]; for (let i = next.length - 1; i; i--) { const j = Math.floor(random() * (i + 1)); [next[i], next[j]] = [next[j], next[i]]; } return next; }
  const LEVELS = [{ name: 'EUPHEMISM', note: 'Harm named indirectly. Read for what is being concealed.' }, { name: 'SIGNAL', note: 'The language begins to declare itself.' }, { name: 'DIRECTIVE', note: 'Policy becomes a command.' }, { name: 'COLLECTIVE HARM', note: 'Whole populations are made into the target.' }, { name: 'EXPLICIT VIOLENCE', note: 'No euphemism left. The source matters most.' }];
  function levelOf(record) { const q = record.quote.toLowerCase(); if (/exterminat|annihilat|kill this people|all of them killed|everyone has one sentence|must be burned|erase .*completely|bomb without distinction|every child|every baby|2 million civilians to die/.test(q)) return 5; if (/no electricity|no food|no fuel|starvation|hunger|destruction|no population|terrorists|uninvolved civilians|occupation|expulsion|settlement|flattened/.test(q)) return 4; if (/race.*eliminated|lice|microbe|slaves|must be destroyed|no reason.*feed|one .*life|taking down/.test(q)) return 3; if (/nakba|common goal|moral right|duty|liquidated|gas vans/.test(q)) return 2; return 1; }
  function makeDeck(mode, first) { const random = mode === 'daily' ? seeded(`who-said-it:${today}`) : Math.random; if (first) return shuffleWith([first, ...shuffleWith(BANK.filter((d) => d !== first), random).slice(0, 4)], random); return LEVELS.map((_, index) => shuffleWith(BANK.filter((record) => levelOf(record) === index + 1), random)[0]); }

  const modeBar = document.createElement('section'); modeBar.className = 'mode-bar'; modeBar.setAttribute('aria-label', 'Game mode'); modeBar.innerHTML = `<div class="mono">CHOOSE A FORMAT</div><div class="mode-buttons"><button data-mode="quick" class="active">QUICK FIVE<small>Five sourced records</small></button><button data-mode="streak">STREAK<small>Keep a run alive</small></button><button data-mode="timeline">TIMELINE<small>Place it before you name it</small></button><button data-mode="daily">DAILY SET<small>${today}</small></button></div>`; document.querySelector('.track')?.insertAdjacentElement('beforebegin', modeBar);
  const wager = document.createElement('section'); wager.className = 'wager'; wager.innerHTML = `<div class="mono">HOW SURE ARE YOU?</div><div class="wager-buttons" role="group" aria-label="Confidence wager"><button data-wager="guess" aria-pressed="false">GUESS <small>+1</small></button><button data-wager="likely" aria-pressed="false">LIKELY <small>+2</small></button><button data-wager="certain" aria-pressed="false">CERTAIN <small>+3</small></button></div><p id="wagerHint">Choose a confidence level, then identify the speaker.</p>`; $('choices')?.insertAdjacentElement('beforebegin', wager);
  const timeline = document.createElement('section'); timeline.className = 'timeline-gate panelHide'; timeline.innerHTML = `<div class="mono">FIRST, PLACE THE RECORD</div><p>Did this statement come before 1945 or after 2020?</p><div><button data-era="before">BEFORE 1945</button><button data-era="after">AFTER 2020</button></div>`; $('choices')?.insertAdjacentElement('beforebegin', timeline);
  const recap = document.createElement('section'); recap.className = 'recap'; recap.id = 'recap'; $('results')?.append(recap);
  const eyebrow = document.querySelector('.eyebrow'); if (eyebrow) eyebrow.textContent = 'THE ATTRIBUTION TEST · SOURCE-LINKED RECORDS · FOUR WAYS TO PLAY';
  const levelMap = document.createElement('section'); levelMap.className = 'level-map'; levelMap.innerHTML = `<div class="level-map-head"><span class="mono">CASE ROUTE</span><span id="levelMicro" class="mono"></span></div><div class="level-nodes">${LEVELS.map((level, index) => `<div class="level-node" data-level-node="${index + 1}"><b>0${index + 1}</b><span>${level.name}</span></div>`).join('')}</div><p>Each level masks more of the clue. It traces escalating directness in the language, never a hierarchy of suffering.</p>`; document.querySelector('.track')?.insertAdjacentElement('beforebegin', levelMap);
  const levelCard = document.createElement('div'); levelCard.className = 'level-card'; levelCard.innerHTML = `<span class="mono" id="levelTag"></span><strong id="levelName"></strong><small id="levelNote"></small>`; document.querySelector('.paper')?.firstElementChild?.insertAdjacentElement('afterend', levelCard);

  function updateHeader() { const best = store.get(); const record = deck[idx]; const level = record ? levelOf(record) : 1; const label = session.mode === 'daily' ? `DAILY SET · ${today}` : session.mode.toUpperCase(); $('scoreText').textContent = `POINTS ${String(session.points).padStart(2, '0')} · STREAK ${session.streak}`; $('roundText').textContent = `${label} · LEVEL ${String(level).padStart(2, '0')} / 05`; let meta = $('sessionMeta'); if (!meta) { meta = document.createElement('span'); meta.id = 'sessionMeta'; meta.className = 'session-meta'; document.querySelector('.boardHead')?.append(meta); } meta.innerHTML = `SOURCE BANK <b>${audit.records} INDEXED RECORDS</b> · BEST <b>${best} PTS</b>`; document.body.dataset.level = String(level); $('levelMicro').textContent = `LEVEL ${String(level).padStart(2, '0')} / 05`; $('levelTag').textContent = `LEVEL ${String(level).padStart(2, '0')} · ${label}`; $('levelName').textContent = LEVELS[level - 1].name; $('levelNote').textContent = LEVELS[level - 1].note; document.querySelectorAll('[data-level-node]').forEach((node) => node.classList.toggle('active', Number(node.dataset.levelNode) === level)); }
  function prepareRound() { session.confidence = null; session.timelineReady = session.mode !== 'timeline'; session.timelineCorrect = null; wager.querySelectorAll('[data-wager]').forEach((b) => b.setAttribute('aria-pressed', 'false')); $('wagerHint').textContent = 'Choose a confidence level, then identify the speaker.'; timeline.classList.toggle('panelHide', session.mode !== 'timeline'); if (session.mode === 'timeline') { timeline.querySelectorAll('button').forEach((b) => { b.disabled = false; b.className = ''; }); [...$('choices').children].forEach((b) => { b.disabled = true; }); } $('reveal')?.querySelector('.reveal-layers')?.remove(); const level = levelOf(deck[idx]); if (level > 3) { const words = $('quoteText').textContent.split(/(\s+)/); let redactions = level - 3; words.forEach((word, position) => { if (redactions && word.length > 7 && !word.includes('[')) { words[position] = '██████'; redactions--; } }); $('quoteText').textContent = words.join(''); } updateHeader(); }
  function startGame(mode = session.mode, first) { session.mode = mode; session.points = 0; session.streak = 0; session.bestStreak = 0; session.rounds = []; deck = makeDeck(mode, first); idx = 0; score = 0; answered = false; $('results').classList.remove('show'); $('playBoard').classList.remove('panelHide'); $('fill').style.width = '0%'; $('track').setAttribute('aria-valuenow', '0'); show('play'); render(); prepareRound(); modeBar.querySelectorAll('[data-mode]').forEach((b) => b.classList.toggle('active', b.dataset.mode === mode)); }
  function setConfidence(value) { session.confidence = value; wager.querySelectorAll('[data-wager]').forEach((b) => b.setAttribute('aria-pressed', String(b.dataset.wager === value))); $('wagerHint').textContent = `${value.toUpperCase()} wager locked. Now make the attribution.`; }
  function showLayers() { const reveal = $('reveal'); if (!reveal) return; const items = [$('speaker'), $('metadata'), $('original'), $('context'), reveal.querySelector('.sources')].filter(Boolean); items.forEach((item) => item.classList.add('reveal-layer-hidden')); const layers = document.createElement('div'); layers.className = 'reveal-layers'; const steps = [{ label: 'REVEAL SPEAKER →', nodes: items.slice(0, 2) }, { label: 'REVEAL ORIGINAL WORDING + CONTEXT →', nodes: items.slice(2, 4) }, { label: 'OPEN THE SOURCE RECORD →', nodes: items.slice(4) }]; function addStep(position) { const step = steps[position]; if (!step) return; const button = document.createElement('button'); button.className = 'minor'; button.textContent = step.label; button.addEventListener('click', () => { step.nodes.forEach((node) => node.classList.remove('reveal-layer-hidden')); button.remove(); addStep(position + 1); }); layers.append(button); } addStep(0); reveal.querySelector('#revealLabel')?.insertAdjacentElement('afterend', layers); }
  function afterAnswer(choice) { const record = deck[idx]; const correct = choice.dataset.group === record.group; const wagerValue = { guess: 1, likely: 2, certain: 3 }[session.confidence] || 0; const earned = correct ? wagerValue + (session.timelineCorrect ? 1 : 0) : 0; session.points += earned; session.streak = correct ? session.streak + 1 : 0; session.bestStreak = Math.max(session.bestStreak, session.streak); store.set(Math.max(store.get(), session.points)); session.rounds.push({ id: record.id, speaker: record.speaker, correct, confidence: session.confidence, earned }); $('feedback').textContent = correct ? `Attribution recorded: +${earned} point${earned === 1 ? '' : 's'}. Reveal the record in your own order.` : 'Not this record. Open the layers below and compare the original source.'; $('next').textContent = session.mode === 'streak' && !correct ? 'VIEW STREAK RESULT →' : idx === deck.length - 1 && session.mode !== 'streak' ? 'VIEW RESULTS →' : 'NEXT STATEMENT →'; updateHeader(); showLayers(); }
  function renderRecap() { recap.replaceChildren(); const heading = document.createElement('div'); heading.className = 'mono'; heading.textContent = 'THE RECORDS YOU MET'; recap.append(heading); const list = document.createElement('div'); list.className = 'recap-list'; session.rounds.forEach((round, position) => { const row = document.createElement('div'); row.innerHTML = `<span>${String(position + 1).padStart(2, '0')}</span><strong>${round.speaker}</strong><small>${round.correct ? `+${round.earned} PTS` : 'REVIEWED'} · ${round.confidence || 'NO WAGER'}</small>`; list.append(row); }); recap.append(list); const note = document.createElement('p'); note.textContent = 'The pattern is the record: different dates, sources and speakers, each linked to its original context.'; recap.append(note); }
  async function shareDaily() { const text = `WHO SAID IT? · DAILY SET ${today}\n${session.points} points · ${session.rounds.filter((r) => r.correct).length}/${session.rounds.length} correct · best streak ${session.bestStreak}\nSource-linked records, read in context.`; try { if (navigator.share) await navigator.share({ title: 'WHO SAID IT?', text }); else await navigator.clipboard.writeText(text); $('shareDaily').textContent = navigator.share ? 'SHARE READY' : 'COPIED'; } catch {} }
  function finishGame() { $('playBoard').classList.add('panelHide'); $('results').classList.add('show'); $('fill').style.width = '100%'; $('finalScore').textContent = `${session.points} POINTS`; $('finalMessage').textContent = `${session.rounds.filter((r) => r.correct).length} attributions correct · best streak ${session.bestStreak}. Every record below stays linked to its source.`; renderRecap(); let share = $('shareDaily'); if (session.mode === 'daily' && !share) { share = document.createElement('button'); share.id = 'shareDaily'; share.className = 'minor'; share.textContent = 'COPY DAILY RESULT'; share.addEventListener('click', shareDaily); $('again').insertAdjacentElement('afterend', share); } if (session.mode !== 'daily') share?.remove(); $('results').scrollIntoView({ behavior: 'smooth', block: 'center' }); }
  function advance() { const last = session.rounds.at(-1); if (session.mode === 'streak' && !last?.correct) return finishGame(); idx += 1; if (session.mode === 'streak' && idx >= deck.length) { deck = makeDeck('streak'); idx = 0; } else if (idx >= deck.length) return finishGame(); render(); prepareRound(); $('track').scrollIntoView({ behavior: 'smooth', block: 'center' }); }
  function challenge(record) { startGame('quick', record); $('feedback').textContent = 'Archive challenge loaded. Choose your confidence level, then make the attribution.'; }
  function augmentArchive() { [...$('records').children].forEach((row) => { if (row.querySelector('.challenge-record')) return; const href = row.querySelector('a')?.href; const record = BANK.find((d) => d.url === href); if (!record) return; const button = document.createElement('button'); button.className = 'challenge-record'; button.textContent = 'CHALLENGE THIS RECORD →'; button.addEventListener('click', () => challenge(record)); row.querySelector('.other')?.append(button); }); }
  new MutationObserver(augmentArchive).observe($('records'), { childList: true });
  modeBar.addEventListener('click', (e) => { const b = e.target.closest('[data-mode]'); if (b) startGame(b.dataset.mode); }); wager.addEventListener('click', (e) => { const b = e.target.closest('[data-wager]'); if (b) setConfidence(b.dataset.wager); }); timeline.addEventListener('click', (e) => { const b = e.target.closest('[data-era]'); if (!b || !deck[idx]) return; const expected = deck[idx].group === 'nazi' ? 'before' : 'after'; session.timelineCorrect = b.dataset.era === expected; session.timelineReady = true; timeline.querySelectorAll('button').forEach((item) => { item.disabled = true; item.classList.toggle('good', item.dataset.era === expected); item.classList.toggle('bad', item === b && !session.timelineCorrect); }); [...$('choices').children].forEach((item) => { item.disabled = false; }); $('feedback').textContent = session.timelineCorrect ? 'Timeline placed. A correct attribution earns one additional point.' : 'Timeline noted. Now identify the speaker.'; });
  document.addEventListener('click', (e) => { const choice = e.target.closest('.choice'); if (choice && !answered) { if (!session.confidence) { e.preventDefault(); e.stopImmediatePropagation(); $('feedback').textContent = 'Choose GUESS, LIKELY or CERTAIN first.'; return; } if (!session.timelineReady) { e.preventDefault(); e.stopImmediatePropagation(); $('feedback').textContent = 'Place the record on the timeline first.'; return; } window.setTimeout(() => afterAnswer(choice), 0); } if (e.target.closest('#next') && answered) { e.preventDefault(); e.stopImmediatePropagation(); advance(); } if (e.target.closest('#again')) { e.preventDefault(); e.stopImmediatePropagation(); startGame(session.mode); } }, true);
  document.addEventListener('keydown', (e) => { if (e.key.toLowerCase() === 'n' && answered && !e.metaKey && !e.ctrlKey && !e.altKey) { e.preventDefault(); advance(); } });
  const originalShow = show; show = function enhancedShow(section) { originalShow(section); if (section === 'archive') window.setTimeout(augmentArchive, 0); };
  if (location.hash === '#archive') show('archive'); else startGame('quick');
  window.__whoSaidIt = Object.freeze({ audit, start: startGame, state: () => ({ mode: session.mode, points: session.points, streak: session.streak, round: idx + 1, answered }) });
})();
